Update Node snippet in README to use `Buffer`
From what I've gathered, the 0.9.x branch of `@minify-html/node` requires a `Buffer` argument.

Update the README to match.

As an aside, passing a string to `minify` gives a somewhat opaque Rust-specific error about downcast failure:

```
TypeError: failed to downcast any to Buffer
```